name: 
  en: Michael Musty
description: 
  en: Number Theory and Computations
footer:
  en: made with [polyglot-jekyll](https://github.com/mrzool/polyglot-jekyll)
exclude: [README.md]
permalink: pretty
plugins:
  - jemoji
